#!/bin/sh

### BEGIN INIT INFO
# Provides:          watchmine
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

. /lib/lsb/init-functions

# Must be a valid filename
NAME=watchmine
PIDFILE=/var/run/$NAME.pid
USER=ethos
#This is the command to be run, give the full pathname
DAEMON=/usr/local/bin/watchmine
DAEMON_OPTS=""

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
        start-stop-daemon --start --background --quiet --user $USER --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        echo "."
        ;;
  stop)
        echo -n "Stopping daemon: "$NAME
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        echo "."
        ;;
  restart)
        echo -n "Restarting daemon: "$NAME
        start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
        start-stop-daemon --start --background --quiet --user $USER --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $DAEMON_OPTS
        echo "."
        ;;
  status)
        echo -n "Status daemon: "$NAME
        start-stop-daemon --status --verbose --oknodo --pidfile $PIDFILE
        echo "."
        ;;
  *)
        echo "Usage: "$1" {start|stop|status|restart}"
        exit 1
esac

exit 0